
use Formula1


/* b*/
SELECT P.NOME, P.PAIS_ORIGEM, P.EQUIPE_ID
FROM PILOTO P
WHERE EQUIPE_ID = (SELECT EQUIPE_ID FROM EQUIPE 
 WHERE NOME = 'Ferrari')

 
SELECT P.NOME,
		P.PAIS_ORIGEM,
		E.NOME AS EQUIPE
		FROM PILOTO P
		INNER JOIN EQUIPE E ON E.EQUIPE_ID = P.EQUIPE_ID
		WHERE
		E.NOME = 'Ferrari'

/* c*/
SELECT P.NOME, P.PAIS_ORIGEM
	,NOME_EQUIPE = (SELECT E.NOME FROM EQUIPE E WHERE E.EQUIPE_ID = P.EQUIPE_ID)
	FROM PILOTO P

/* d*/
SELECT PAIS_ORIGEM,
NOME,
COUNT(*) AS QTD_PAIS
 FROM PILOTO
GROUP BY PAIS_ORIGEM, NOME


------

SELECT COUNT(*) AS QTD_PAIS
FROM PILOTO


/* e*/
SELECT PAIS 
 FROM GRANDE_PREMIO
WHERE MONTH(DATA) = 3

/* f*/
SELECT P.PILOTO_ID, P.NOME, MAX(POSICAO) AS WORST_POSITION
 FROM COLOCACAO C
 INNER JOIN PILOTO P ON P.PILOTO_ID = C.PILOTO_ID
WHERE C.PILOTO_ID = 2

GROUP BY P.NOME, P.PILOTO_ID

