SELECT F.CODFITA, F.NOME, F.COR, P.VALOR, F.STATUS,F.CODGENERO,L.DATA AS 'UltimaLocaçao', L.DATADEVOLUCAO, G.DESCRICAO, C.NOME AS 'CLIENTE'

FROM LOCACAO L
	INNER JOIN 
		FITA F ON L.CODFITA = F.CODFITA
	INNER JOIN 
		PRECO P ON F.COR = P.COR
	INNER JOIN 
		GENERO G ON G.CODGENERO = F.CODGENERO
	INNER JOIN 
		CLIENTE C ON L.CODCLIENTE = C.CODCLIENTE


SELECT C.NOME, F.NOME, L.DATA

FROM LOCACAO L
	INNER JOIN 
		FITA F ON L.CODFITA = F.CODFITA
	INNER JOIN 
		CLIENTE C ON C.CODCLIENTE = L.CODCLIENTE



SELECT * FROM LOCACAO
SELECT * FROM CLIENTE
SELECT * FROM FITA