
/*
1) PILOTOS CUJO NOME COMEÇA POR "A" OU POR "F"
*/

SELECT P. NOME
FROM EQUIPE E
INNER JOIN PILOTO P ON E.EQUIPE_ID = P.EQUIPE_ID
WHERE (P.NOME LIKE 'A%') OR (p.nome like 'f%')

/*
2) NOME DE CADA PILOTO E A QUANTIDADE DE CARACTERES DO SEU NOME
*/

SELECT 
	P.NOME,
	LEN(REPLACE(P.NOME, ' ', '')) AS TAMANHO
FROM PILOTO P;


/* 
3) NOME INVERTIDO (DE TRÁS PARA FRENTE) DE CADA PILOTO
*/

SELECT 
	P.NOME,
	REVERSE(P.NOME) AS REVERSENAME
FROM PILOTO P;


/*
4) O NOME E OS TRÊS ÚLTIMOS CARACTERES DO NOME, PARA CADA EQUIPE
*/

SELECT 
    E.NOME,
	RIGHT(E.NOME,3) AS LAST3
FROM EQUIPE E;


/*
5) O PAÍS DO GRANDE PREMIO E O MÊS DE REALIZAÇÃO, ORDERNADO PELA DATA 
DE REALIZAÇÃO DE FORMA DESCENDENTE
*/

SELECT 
	G.PAIS,
	MONTH(G.DATA) AS MES
FROM GRANDE_PREMIO G
ORDER BY G.DATA DESC


/*
6) GRANDES PRÊMIOS CUJO O NOME DO PAIS COMECE COM UMA VOGAL E O DIA DE
REALIZAÇÃO SEJA INFERIOR A 10
*/

SELECT 
	G.GP_ID,
	G.PAIS,
	DAY(G.DATA) AS DIA
FROM GRANDE_PREMIO G
WHERE (G.PAIS LIKE '[aeiou]%') AND (DAY(G.DATA) < 10);


/*
7) O NOME DO GRANDE PRÊMIO E HÁ QUANTOS MESES FOI REALIZADO
*/


SELECT 
	GP.PAIS,
	GP.DATA AS DATA,
	DATEDIFF(MONTH, GP.DATA, GETDATE()) AS DiferencaEmMeses
FROM GRANDE_PREMIO GP
