CREATE DATABASE LOCADORA
go

USE LOCADORA
go

CREATE TABLE CLIENTE (
       CODCLIENTE           int NOT NULL,
       NOME                 varchar(50) NOT NULL,
       ENDERECO             varchar(50),
       BAIRRO               varchar(20),
       CIDADE               varchar(50),
       ESTADO               char(2)
)
go

ALTER TABLE CLIENTE
       ADD PRIMARY KEY (CODCLIENTE)
go


CREATE TABLE FITA (
       CODFITA              int NOT NULL,
       NOME                 varchar(50) NOT NULL,
       COR                  char(2) NOT NULL,
       STATUS               char(1) NOT NULL,
       CODGENERO            int NOT NULL
)
go


ALTER TABLE FITA
       ADD PRIMARY KEY (CODFITA)
go


CREATE TABLE GENERO (
       CODGENERO            int NOT NULL,
       DESCRICAO            varchar(20) NOT NULL
)
go


ALTER TABLE GENERO
       ADD PRIMARY KEY (CODGENERO)
go


CREATE TABLE LOCACAO (
       CODCLIENTE           int NOT NULL,
       DATA                 datetime NOT NULL,
       CODFITA              int NOT NULL,
       DATADEVOLUCAO        datetime
)
go


ALTER TABLE LOCACAO
       ADD PRIMARY KEY (CODCLIENTE, DATA, CODFITA)
go


CREATE TABLE PRECO (
       COR                  char(2) NOT NULL,
       VALOR                float NOT NULL
)
go


ALTER TABLE PRECO
       ADD PRIMARY KEY (COR)
go


ALTER TABLE FITA
       ADD FOREIGN KEY (CODGENERO)
                             REFERENCES GENERO
go


ALTER TABLE FITA
       ADD FOREIGN KEY (COR)
                             REFERENCES PRECO
go


ALTER TABLE LOCACAO
       ADD FOREIGN KEY (CODCLIENTE)
                             REFERENCES CLIENTE
go


ALTER TABLE LOCACAO
       ADD FOREIGN KEY (CODFITA)
                             REFERENCES FITA
go


INSERT INTO PRECO (COR, VALOR) VALUES
('BR', 2.0)
GO
INSERT INTO PRECO (COR, VALOR) VALUES
('AZ', 2.5)
GO
INSERT INTO PRECO (COR, VALOR) VALUES
('PR', 3.0)
GO
INSERT INTO PRECO (COR, VALOR) VALUES
('VD', 3.5)
GO
INSERT INTO PRECO (COR, VALOR) VALUES
('AM', 4.0)
GO
INSERT INTO PRECO (COR, VALOR) VALUES
('VM', 4.5)
GO

INSERT INTO GENERO (CODGENERO, DESCRICAO) VALUES
(1, 'Romance')
GO
INSERT INTO GENERO (CODGENERO, DESCRICAO) VALUES
(2, 'Drama')
GO
INSERT INTO GENERO (CODGENERO, DESCRICAO) VALUES
(3, 'Comédia')
GO
INSERT INTO GENERO (CODGENERO, DESCRICAO) VALUES
(4, 'Aventura')
GO
INSERT INTO GENERO (CODGENERO, DESCRICAO) VALUES
(5, 'Policial')
GO
INSERT INTO GENERO (CODGENERO, DESCRICAO) VALUES
(6, 'Suspense')
GO
INSERT INTO GENERO (CODGENERO, DESCRICAO) VALUES
(7, 'Guerra')
GO
INSERT INTO GENERO (CODGENERO, DESCRICAO) VALUES
(8, 'Ação')
GO

INSERT INTO FITA (CODFITA, NOME, COR, CODGENERO, STATUS) VALUES
(200, 'Matrix', 'VM', 8, 'L')
GO
INSERT INTO FITA (CODFITA, NOME, COR, CODGENERO, STATUS) VALUES
(210, 'Os Normais', 'AM', 3, 'L')
GO
INSERT INTO FITA (CODFITA, NOME, COR, CODGENERO, STATUS) VALUES
(220, 'Titanic', 'VD', 1, 'D')
GO
INSERT INTO FITA (CODFITA, NOME, COR, CODGENERO, STATUS) VALUES
(230, 'Guerra nas Estrelas', 'BR', 4, 'L')
GO
INSERT INTO FITA (CODFITA, NOME, COR, CODGENERO, STATUS) VALUES
(240, 'À espera de um milagre', 'PR', 6, 'D')
GO
INSERT INTO FITA (CODFITA, NOME, COR, CODGENERO, STATUS) VALUES
(250, 'O sexto sentido', 'PR', 6, 'L')
GO
INSERT INTO FITA (CODFITA, NOME, COR, CODGENERO, STATUS) VALUES
(260, 'Além da linha vermelha', 'VD', 7, 'D')
GO
INSERT INTO FITA (CODFITA, NOME, COR, CODGENERO, STATUS) VALUES
(270, 'Robocop', 'BR', 5, 'I')
GO
INSERT INTO FITA (CODFITA, NOME, COR, CODGENERO, STATUS) VALUES
(280, 'O resgate do soldado Rian', 'PR', 7, 'L')
GO
INSERT INTO FITA (CODFITA, NOME, COR, CODGENERO, STATUS) VALUES
(290, 'Top Gang', 'PR', 3, 'D')
GO


INSERT INTO CLIENTE (CODCLIENTE, NOME, ENDERECO, BAIRRO, CIDADE, ESTADO) VALUES
(100, 'João da Silva', 'Av. Amazonas, 100/101', 'Centro', 'Belo Horizonte', 'MG')
GO
INSERT INTO CLIENTE (CODCLIENTE, NOME, ENDERECO, BAIRRO, CIDADE, ESTADO) VALUES
(110, 'Maria José de Souza', 'Rua Curitiba, 1009/102', 'Centro', 'Belo Horizonte', 'MG')
GO
INSERT INTO CLIENTE (CODCLIENTE, NOME, ENDERECO, BAIRRO, CIDADE, ESTADO) VALUES
(120, 'Antônio Carlos Ferreira', 'Rua Piauí, 200/501', 'Funcionários', 'Belo Horizonte', 'MG')
GO
INSERT INTO CLIENTE (CODCLIENTE, NOME, ENDERECO, BAIRRO, CIDADE, ESTADO) VALUES
(130, 'Patrícia dos Santos', 'Rua Paraíba, 300/902', 'Funcionários', 'Sete Lagoas', 'MG')
GO
INSERT INTO CLIENTE (CODCLIENTE, NOME, ENDERECO, BAIRRO, CIDADE, ESTADO) VALUES
(140, 'Paulo Correia', 'Rua Platina, 400/1002', 'Prado', 'Sete Lagoas', 'MG')
GO
INSERT INTO CLIENTE (CODCLIENTE, NOME, ENDERECO, BAIRRO, CIDADE, ESTADO) VALUES
(150, 'Daniela Marinho', 'Rua Joaquim Xavier, 300/902', 'Penha', 'Rio de Janeiro', 'RJ')
GO
INSERT INTO CLIENTE (CODCLIENTE, NOME, ENDERECO, BAIRRO, CIDADE, ESTADO) VALUES
(160, 'Fabrícia Passos', 'Rua Álvares Cabral, 4000/502', 'Leblon', 'Rio de Janeiro', 'RJ')
GO
INSERT INTO CLIENTE (CODCLIENTE, NOME, ENDERECO, BAIRRO, CIDADE, ESTADO) VALUES
(170, 'Danilo Passos', 'Pça. D. Pedro I, 890/104', 'Ipanema', 'Rio de Janeiro', 'RJ')
GO
INSERT INTO CLIENTE (CODCLIENTE, NOME, ENDERECO, BAIRRO, CIDADE, ESTADO) VALUES
(180, 'Roberto Assunção', 'Av. Tiradentes, 3500/105', 'Centro', 'São Paulo', 'SP')
GO
INSERT INTO CLIENTE (CODCLIENTE, NOME, ENDERECO, BAIRRO, CIDADE, ESTADO) VALUES
(190, 'Sílvia Cordeiro', 'Av. Paulista, 5500/105', 'Centro', 'São Paulo', 'SP')
GO
INSERT INTO CLIENTE (CODCLIENTE, NOME, ENDERECO, BAIRRO, CIDADE, ESTADO) VALUES
(200, 'Ricardo Andrade', 'Rua da Concórdia, 670/205', 'Centro', 'Jacareí', 'SP')
GO

SET DATEFORMAT YMD

INSERT INTO LOCACAO (CODCLIENTE, DATA, CODFITA, DATADEVOLUCAO) VALUES
(100, '2003-01-20', 270, '2003-01-23')
GO
INSERT INTO LOCACAO (CODCLIENTE, DATA, CODFITA, DATADEVOLUCAO) VALUES
(110, '2003-03-22', 260, '2003-03-25')
GO
INSERT INTO LOCACAO (CODCLIENTE, DATA, CODFITA, DATADEVOLUCAO) VALUES
(110, '2003-10-20', 250, NULL)
GO
INSERT INTO LOCACAO (CODCLIENTE, DATA, CODFITA, DATADEVOLUCAO) VALUES
(120, '2003-10-05', 230, NULL)
GO
INSERT INTO LOCACAO (CODCLIENTE, DATA, CODFITA, DATADEVOLUCAO) VALUES
(130, '2003-10-10', 280, NULL)
GO
INSERT INTO LOCACAO (CODCLIENTE, DATA, CODFITA, DATADEVOLUCAO) VALUES
(140, '2003-01-20', 250, '2003-01-23')
GO
INSERT INTO LOCACAO (CODCLIENTE, DATA, CODFITA, DATADEVOLUCAO) VALUES
(150, '2003-01-20', 270, '2003-01-23')
GO
INSERT INTO LOCACAO (CODCLIENTE, DATA, CODFITA, DATADEVOLUCAO) VALUES
(150, '2003-02-10', 260, '2003-02-13')
GO
INSERT INTO LOCACAO (CODCLIENTE, DATA, CODFITA, DATADEVOLUCAO) VALUES
(150, '2003-09-10', 290, '2003-09-12')
GO
INSERT INTO LOCACAO (CODCLIENTE, DATA, CODFITA, DATADEVOLUCAO) VALUES
(160, '2003-07-30', 200, NULL)
GO
INSERT INTO LOCACAO (CODCLIENTE, DATA, CODFITA, DATADEVOLUCAO) VALUES
(160, '2003-07-30', 210, NULL)
GO
INSERT INTO LOCACAO (CODCLIENTE, DATA, CODFITA, DATADEVOLUCAO) VALUES
(170, '2003-08-03', 270, '2003-08-10')
GO
INSERT INTO LOCACAO (CODCLIENTE, DATA, CODFITA, DATADEVOLUCAO) VALUES
(180, '2003-04-03', 290, '2003-04-05')
GO


